#pragma once

#define WINDOW_HEIGHT 1000.f
#define WINDOW_WIDTH 1500.f
#define FPS_CAP 10000.f

#define GRAVITY 100.f
#define TARGET_SIZE 50
#define TARGET_INITIAL_X WINDOW_WIDTH - 300
#define CANNONBALL_SPEED 2.0f
#define CANNONBALL_SIZE 5
